#!/bin/sh

TODAY=$(date +%F)
YESTERDAY=$(date --date="yesterday" +%F)
NEWDIR=/media/1ntfs/rmaidan/gallery/$TODAY
FILENAME=${1##*/}
echo $NEWDIR $FILENAME
mkdir -p $NEWDIR
mv $1 $NEWDIR/
#ln -s -f $NEWDIR/$FILENAME /media/1ntfs/motion/lastimg.jpg
#ln -s -f $NEWDIR/rmaidan_temp.png /media/1ntfs/motion/temper.png
#igal2 -d $NEWDIR --dest igal2 --pagination 50

if ! grep $TODAY /media/1ntfs/rmaidan/index1.html
then
    cp /media/1ntfs/rmaidan/gallery/index.html /media/1ntfs/rmaidan/gallery/$YESTERDAY.html
    sleep 1s
    cp /media/1ntfs/rmaidan/gallery/.index /media/1ntfs/rmaidan/gallery/index.html
    sleep 1s
    echo \<a href=$TODAY.html\>$TODAY\</a\>\| >> /media/1ntfs/rmaidan/index1.html
fi

NEWLINE="<img src="grey.gif" data-original="$TODAY/$FILENAME"><br/>"

cp /media/1ntfs/rmaidan/gallery/index.html /media/1ntfs/rmaidan/gallery/.tmp
sleep 1s

PATTERN=insertnewimagesafter
while read line
do
        echo $line
        echo $line | grep -q $PATTERN
        [ $? -eq 0 ] && echo $NEWLINE
done < /media/1ntfs/rmaidan/gallery/.tmp > /media/1ntfs/rmaidan/gallery/index.html
